import Head from "next/head";
import Background from "@/components/Background";
import Header from "@/components/Header";
import SectionLogo from "@/components/SectionLogo";
import AboutUs from "@/components/AboutUs";
import Hackathons from "@/components/Hackathons";
import Meetups from "@/components/Meetups";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Background />
      <Head>
        <title>HackFed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <Header />
        <SectionLogo />
        <AboutUs />
        <Hackathons />
        <Meetups />
        <Footer />
        

      </main>
    </>
  );
}
